apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: todo-container
          image: igfred/todo-app:v01  # Use the official Node.js image or your own custom image
          ports:
            - containerPort: 7000

