apiVersion: v1
kind: Service
metadata:
  name: todo-services2
  labels:
    app: todo
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - port: 7000
      targetPort: 7000
      nodePort: 30002

