apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commerce
  template:
    metadata:
      labels:
        app: commerce
    spec:
      containers:
        - name: commerce
          image: igfred/ecommerce:v01  # Use the official Node.js image or your own custom image
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: commerce-svc
  labels:
    app: commerce
spec:
  type: NodePort
  selector:
    app: commerce
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30003
